# Generated by Django 6.0.4 on 2026-05-13 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_has_registration_fee_event_registration_fee'),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stalls', to='events.event'),
        ),
        migrations.AlterField(
            model_name='stall',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stalls', to='owner.owner'),
        ),
    ]
