# Generated by Django 6.0.4 on 2026-05-09 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='event',
        ),
        migrations.AlterField(
            model_name='owner',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='owner',
            name='social_media',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stall',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stall',
            name='event_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stall',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stall',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='owner.owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stall',
            name='rental_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
