# Generated by Django 6.0.4 on 2026-05-09 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_remove_owner_event_alter_owner_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stall',
            name='event_name',
        ),
        migrations.AddField(
            model_name='stall',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stall',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='owner',
            name='social_media',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stall',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stall',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stalls', to='owner.owner'),
        ),
    ]
