# Generated by Django 6.0.4 on 2026-05-10 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('owner', '0003_remove_owner_user_remove_stall_event_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stalls', to='events.event'),
            preserve_default=False,
        ),
    ]
