# Generated by Django 6.0.4 on 2026-05-10 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('owner', '0004_stall_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stalls', to='events.event'),
        ),
    ]
