# Generated by Django 6.0.4 on 2026-06-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_remove_stall_status_stall_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
