# Generated by Django 6.0.4 on 2026-06-08 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_stall_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stall',
            name='status',
        ),
    ]
