# Generated by Django 6.0.4 on 2026-06-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_remove_stall_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
