# Generated by Django 6.0.4 on 2026-05-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_registration_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
