# Generated by Django 6.0.4 on 2026-04-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_created_at_event_image_eventregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
