# Generated by Django 6.0.4 on 2026-04-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_is_approved_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('concert', 'Concert / Viewing Event'), ('tournament', 'Tournament / Competition'), ('bazaar', 'Bazaar / Stall Event')], default='concert', max_length=20),
        ),
    ]
