# Generated by Django 6.0.4 on 2026-06-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_merge_20260606_1407'),
        ('events', '0004_event_team_size_alter_event_id_and_more'),
    ]

    operations = [
    ]
