# Generated by Django 6.0.4 on 2026-04-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_vendors',
            field=models.BooleanField(default=False),
        ),
    ]
