# Generated by Django 6.0.4 on 2026-04-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_allow_vendors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='allow_vendors',
        ),
        migrations.AddField(
            model_name='event',
            name='allow_vendors_collaborators',
            field=models.BooleanField(default=False, verbose_name='Allow vendors / collaborators?'),
        ),
    ]
