# Generated by Django 6.0.4 on 2026-04-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_allow_vendors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='allow_vendors_collaborators',
            field=models.BooleanField(default=False, verbose_name='Allow vendors/collaborators?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('concert', 'Concert / Viewing Event'), ('tournament', 'Tournament / Competition'), ('bazaar', 'Bazaar / Stall Event')], max_length=20),
        ),
    ]
