# Generated by Django 6.0.4 on 2026-04-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventregistration_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_registration_fee',
            field=models.BooleanField(default=False, verbose_name='Enable registration fee?'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Registration Fee (RM)'),
        ),
    ]
