# Generated by Django 6.0.4 on 2026-04-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_has_registration_fee_event_registration_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='allow_vendors_collaborators',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='has_registration_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
