# Generated by Django 6.0.4 on 2026-06-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_vendorregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorregistration',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
