# Generated by Django 6.0.4 on 2026-06-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_vendorregistration_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='has_registration_fee',
            new_name='enable_registration_fee',
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='team_size',
            field=models.PositiveIntegerField(blank=True, help_text='Only used for tournament events', null=True),
        ),
    ]
