# Generated by Django 6.0.4 on 2026-06-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_rename_has_registration_fee_event_enable_registration_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_vendors_collaborators',
            field=models.BooleanField(default=False),
        ),
    ]
