# Generated by Django 6.0.4 on 2026-06-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_allow_vendors_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='team_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
