# Generated by Django 6.0.4 on 2026-06-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_eventregistration_payment_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
