# Generated by Django 6.0.4 on 2026-06-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_bank_account_name_event_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='registration_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
