# Generated by Django 5.2.13 on 2026-04-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approving',
            field=models.BooleanField(default=False),
        ),
    ]
