# Generated by Django 5.2.13 on 2026-05-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('organizer', 'Organizer'), ('vendor', 'Stall Vendor')], default='student', max_length=20),
        ),
    ]
