# Generated by Django 5.2.13 on 2026-05-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_organizer_requested',
            field=models.BooleanField(default=False),
        ),
    ]
